// <auto-generated />
using System;
using ECMS.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECMS.Persistence.Migrations
{
    [DbContext(typeof(EcmsDbContext))]
    partial class EcmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ECMS.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .HasColumnType("longtext");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogsSet");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ContainerNo")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ShippingLineId")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ContainerNo")
                        .IsUnique();

                    b.HasIndex("ShippingLineId");

                    b.ToTable("ContainersSet");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.ContainerSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("Teu")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.ToTable("ContainerSizesSet");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.ContainerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ContainerTypesSet");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.Depot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DepotsSet");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DepotId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EvaluatorId")
                        .HasColumnType("int");

                    b.Property<int>("PreAdviceId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepotId");

                    b.HasIndex("EvaluatorId");

                    b.HasIndex("PreAdviceId")
                        .IsUnique();

                    b.ToTable("EvaluationsSet");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.ManualYardInventoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ContainerNo")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ContainerSizeId")
                        .HasColumnType("int");

                    b.Property<int>("ContainerTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("DepotId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<int>("ShippingLineId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("YardInDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ContainerSizeId");

                    b.HasIndex("ContainerTypeId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DepotId");

                    b.HasIndex("ShippingLineId", "ContainerNo", "DepotId")
                        .IsUnique();

                    b.ToTable("ManualYardInventoryEntriesSet");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LinkPath")
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReferenceNo")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("UserId", "IsRead", "CreatedAt");

                    b.ToTable("NotificationsSet");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokensSet");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProofFile")
                        .HasColumnType("longtext");

                    b.Property<string>("ProofReferenceNo")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ProofQrphInvoiceNo")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ProofProvider")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("ProofTransactionAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TruckerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId")
                        .IsUnique();

                    b.HasIndex("TruckerId");

                    b.ToTable("PaymentsSet");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.PaymentSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("ReturnFeeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("PaymentSettingsSet");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.PreAdvice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ActiveRequestKey")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ContainerId")
                        .HasColumnType("int");

                    b.Property<string>("ContainerNoNormalized")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ContainerSizeId")
                        .HasColumnType("int");

                    b.Property<int>("ContainerTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReferenceNo")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<int>("ShippingLineId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TruckerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActiveRequestKey")
                        .IsUnique();

                    b.HasIndex("ContainerId");

                    b.HasIndex("ContainerSizeId");

                    b.HasIndex("ContainerTypeId");

                    b.HasIndex("ReferenceNo")
                        .IsUnique();

                    b.HasIndex("ShippingLineId");

                    b.HasIndex("TruckerId");

                    b.HasIndex("ContainerNoNormalized", "ContainerSizeId", "ContainerTypeId");

                    b.ToTable("PreAdvicesSet");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.PreAdviceDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("PreAdviceId")
                        .HasColumnType("int");

                    b.Property<int>("UploadedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PreAdviceId");

                    b.HasIndex("UploadedById");

                    b.ToTable("PreAdviceDocumentsSet");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.QRBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LogicteckBookedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LogicteckExternalRef")
                        .HasColumnType("longtext");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QRCode")
                        .IsUnique();

                    b.HasIndex("ScheduleId")
                        .IsUnique();

                    b.ToTable("QRBookingsSet");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokensSet");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AllowedPagesJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RolesSet");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DepotId")
                        .HasColumnType("int");

                    b.Property<string>("DepotRemarks")
                        .HasColumnType("longtext");

                    b.Property<int>("PreAdviceId")
                        .HasColumnType("int");

                    b.Property<int>("SlotNo")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time(6)");

                    b.Property<int?>("TruckerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepotId");

                    b.HasIndex("PreAdviceId")
                        .IsUnique();

                    b.HasIndex("TruckerId");

                    b.ToTable("SchedulesSet");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.ShippingLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ShippingLinesSet");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.ShippingLineDepotContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ContractTeu")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DepotId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ShippingLineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepotId");

                    b.HasIndex("ShippingLineId", "DepotId")
                        .IsUnique();

                    b.ToTable("ShippingLineDepotContractsSet");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.ShippingLineDepotContractSizeAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ContainerSizeId")
                        .HasColumnType("int");

                    b.Property<int>("ContractCount")
                        .HasColumnType("int");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ContainerSizeId");

                    b.HasIndex("ContractId", "ContainerSizeId")
                        .IsUnique();

                    b.ToTable("ShippingLineDepotContractSizeAllocation");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DepotId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfilePhoto")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("ShippingLineId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DepotId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("ShippingLineId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UsersSet");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("ECMS.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.Container", b =>
                {
                    b.HasOne("ECMS.Domain.Entities.ShippingLine", "ShippingLine")
                        .WithMany("Containers")
                        .HasForeignKey("ShippingLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShippingLine");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.Evaluation", b =>
                {
                    b.HasOne("ECMS.Domain.Entities.Depot", "Depot")
                        .WithMany("Evaluations")
                        .HasForeignKey("DepotId");

                    b.HasOne("ECMS.Domain.Entities.User", "Evaluator")
                        .WithMany("Evaluations")
                        .HasForeignKey("EvaluatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECMS.Domain.Entities.PreAdvice", "PreAdvice")
                        .WithOne("Evaluation")
                        .HasForeignKey("ECMS.Domain.Entities.Evaluation", "PreAdviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Depot");

                    b.Navigation("Evaluator");

                    b.Navigation("PreAdvice");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.ManualYardInventoryEntry", b =>
                {
                    b.HasOne("ECMS.Domain.Entities.ContainerSize", "ContainerSize")
                        .WithMany()
                        .HasForeignKey("ContainerSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECMS.Domain.Entities.ContainerType", "ContainerType")
                        .WithMany()
                        .HasForeignKey("ContainerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECMS.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECMS.Domain.Entities.Depot", "Depot")
                        .WithMany()
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECMS.Domain.Entities.ShippingLine", "ShippingLine")
                        .WithMany()
                        .HasForeignKey("ShippingLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContainerSize");

                    b.Navigation("ContainerType");

                    b.Navigation("CreatedBy");

                    b.Navigation("Depot");

                    b.Navigation("ShippingLine");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.Notification", b =>
                {
                    b.HasOne("ECMS.Domain.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ECMS.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("ECMS.Domain.Entities.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.Payment", b =>
                {
                    b.HasOne("ECMS.Domain.Entities.Schedule", "Schedule")
                        .WithOne("Payment")
                        .HasForeignKey("ECMS.Domain.Entities.Payment", "ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECMS.Domain.Entities.User", "Trucker")
                        .WithMany("Payments")
                        .HasForeignKey("TruckerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("Trucker");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.PreAdvice", b =>
                {
                    b.HasOne("ECMS.Domain.Entities.Container", "Container")
                        .WithMany("PreAdvices")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECMS.Domain.Entities.ContainerSize", "ContainerSize")
                        .WithMany()
                        .HasForeignKey("ContainerSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECMS.Domain.Entities.ContainerType", "ContainerType")
                        .WithMany()
                        .HasForeignKey("ContainerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECMS.Domain.Entities.ShippingLine", "ShippingLine")
                        .WithMany("PreAdvices")
                        .HasForeignKey("ShippingLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECMS.Domain.Entities.User", "Trucker")
                        .WithMany("PreAdvices")
                        .HasForeignKey("TruckerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");

                    b.Navigation("ContainerSize");

                    b.Navigation("ContainerType");

                    b.Navigation("ShippingLine");

                    b.Navigation("Trucker");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.PreAdviceDocument", b =>
                {
                    b.HasOne("ECMS.Domain.Entities.PreAdvice", "PreAdvice")
                        .WithMany("Documents")
                        .HasForeignKey("PreAdviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECMS.Domain.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreAdvice");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.QRBooking", b =>
                {
                    b.HasOne("ECMS.Domain.Entities.Schedule", "Schedule")
                        .WithOne("QRBooking")
                        .HasForeignKey("ECMS.Domain.Entities.QRBooking", "ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ECMS.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.Schedule", b =>
                {
                    b.HasOne("ECMS.Domain.Entities.Depot", "Depot")
                        .WithMany("Schedules")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECMS.Domain.Entities.PreAdvice", "PreAdvice")
                        .WithOne("Schedule")
                        .HasForeignKey("ECMS.Domain.Entities.Schedule", "PreAdviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECMS.Domain.Entities.User", "Trucker")
                        .WithMany()
                        .HasForeignKey("TruckerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Depot");

                    b.Navigation("PreAdvice");

                    b.Navigation("Trucker");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.ShippingLineDepotContract", b =>
                {
                    b.HasOne("ECMS.Domain.Entities.Depot", "Depot")
                        .WithMany()
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECMS.Domain.Entities.ShippingLine", "ShippingLine")
                        .WithMany()
                        .HasForeignKey("ShippingLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Depot");

                    b.Navigation("ShippingLine");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.ShippingLineDepotContractSizeAllocation", b =>
                {
                    b.HasOne("ECMS.Domain.Entities.ContainerSize", "ContainerSize")
                        .WithMany()
                        .HasForeignKey("ContainerSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECMS.Domain.Entities.ShippingLineDepotContract", "Contract")
                        .WithMany("SizeAllocations")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContainerSize");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.User", b =>
                {
                    b.HasOne("ECMS.Domain.Entities.Depot", "Depot")
                        .WithMany("Users")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ECMS.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECMS.Domain.Entities.ShippingLine", "ShippingLine")
                        .WithMany("Users")
                        .HasForeignKey("ShippingLineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Depot");

                    b.Navigation("Role");

                    b.Navigation("ShippingLine");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.Container", b =>
                {
                    b.Navigation("PreAdvices");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.Depot", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("Schedules");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.PreAdvice", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Evaluation");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.Schedule", b =>
                {
                    b.Navigation("Payment");

                    b.Navigation("QRBooking");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.ShippingLine", b =>
                {
                    b.Navigation("Containers");

                    b.Navigation("PreAdvices");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.ShippingLineDepotContract", b =>
                {
                    b.Navigation("SizeAllocations");
                });

            modelBuilder.Entity("ECMS.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Evaluations");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("Payments");

                    b.Navigation("PreAdvices");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
