export type CertificateDocumentType = 'Atw' | 'AtwRelease' | 'CyContainerRelease'

export const CERTIFICATE_DOCUMENT_TYPES: {
  value: CertificateDocumentType
  label: string
  description: string
}[] = [
  { value: 'Atw', label: 'ATW Issue', description: 'Authority to Withdraw issued by shipping line' },
  { value: 'AtwRelease', label: 'ATW Release', description: 'Full ATW release when all containers are released' },
  { value: 'CyContainerRelease', label: 'CY Container Release', description: 'Per-container release from CY' },
]

export function documentTypeLabel(documentType: CertificateDocumentType): string {
  return CERTIFICATE_DOCUMENT_TYPES.find((t) => t.value === documentType)?.label ?? documentType
}

export function getDefaultLayout(documentType: CertificateDocumentType): CertificateLayoutDefinition {
  switch (documentType) {
    case 'AtwRelease':
      return DEFAULT_ATW_RELEASE_LAYOUT
    case 'CyContainerRelease':
      return DEFAULT_CY_CONTAINER_RELEASE_LAYOUT
    default:
      return DEFAULT_ATW_LAYOUT
  }
}

export type CertificateElementType = 'title' | 'text' | 'field' | 'table' | 'spacer' | 'rule' | 'image'

export interface CertificatePageSettings {
  size: string
  marginMm: number
}

export interface CertificateLayoutDefinition {
  version: number
  page: CertificatePageSettings
  elements: CertificateLayoutElement[]
}

export interface CertificateLayoutElementBase {
  type: CertificateElementType
}

export interface CertificateTitleElement extends CertificateLayoutElementBase {
  type: 'title'
  text: string
  align: string
  fontSize: number
  bold: boolean
}

export interface CertificateTextElement extends CertificateLayoutElementBase {
  type: 'text'
  text: string
  align: string
  fontSize: number
  bold: boolean
}

export interface CertificateFieldElement extends CertificateLayoutElementBase {
  type: 'field'
  label: string
  binding: string
  fontSize: number
  bold: boolean
}

export interface CertificateTableElement extends CertificateLayoutElementBase {
  type: 'table'
  binding: string
  columns: string[]
  fontSize: number
}

export interface CertificateSpacerElement extends CertificateLayoutElementBase {
  type: 'spacer'
  heightMm: number
}

export interface CertificateRuleElement extends CertificateLayoutElementBase {
  type: 'rule'
  thicknessPt: number
}

export interface CertificateImageElement extends CertificateLayoutElementBase {
  type: 'image'
  src: string
  align: string
  widthMm: number
  heightMm?: number
  alt?: string
}

export type CertificateLayoutElement =
  | CertificateTitleElement
  | CertificateTextElement
  | CertificateFieldElement
  | CertificateTableElement
  | CertificateSpacerElement
  | CertificateRuleElement
  | CertificateImageElement

export interface CertificateTemplate {
  id: number
  shippingLineId: number
  shippingLineName: string
  documentType: CertificateDocumentType
  name: string
  layoutJson: string
  isActive: boolean
  updatedAt: string
  createdAt: string
}

export interface CertificateMergeField {
  key: string
  label: string
  kind: 'field' | 'table'
}

export const DEFAULT_ATW_LAYOUT: CertificateLayoutDefinition = {
  version: 1,
  page: { size: 'A4', marginMm: 20 },
  elements: [
    { type: 'title', text: 'AUTHORITY TO WITHDRAW', align: 'center', fontSize: 18, bold: true },
    { type: 'spacer', heightMm: 6 },
    { type: 'field', label: 'ATW No.', binding: 'AtwNumber', fontSize: 11, bold: true },
    { type: 'field', label: 'Reference', binding: 'ReferenceNo', fontSize: 11, bold: false },
    { type: 'field', label: 'Shipping line', binding: 'ShippingLineName', fontSize: 11, bold: false },
    { type: 'field', label: 'Authorized trucker', binding: 'TruckerName', fontSize: 11, bold: false },
    { type: 'field', label: 'Current CY', binding: 'CurrentDepotName', fontSize: 11, bold: false },
    { type: 'field', label: 'Destination', binding: 'Destination', fontSize: 11, bold: false },
    { type: 'field', label: 'Issue date', binding: 'IssueDate', fontSize: 11, bold: false },
    { type: 'field', label: 'Expiration date', binding: 'ExpirationDate', fontSize: 11, bold: false },
    { type: 'spacer', heightMm: 4 },
    {
      type: 'text',
      text: 'The following container(s) are authorized for withdrawal from CY inventory:',
      align: 'left',
      fontSize: 10,
      bold: false,
    },
    { type: 'table', binding: 'ContainerLines', columns: ['ContainerNo', 'Size', 'Type'], fontSize: 10 },
    { type: 'spacer', heightMm: 4 },
    { type: 'field', label: 'Remarks', binding: 'Remarks', fontSize: 11, bold: false },
    { type: 'spacer', heightMm: 8 },
    {
      type: 'text',
      text: 'This document is system-generated by ICS and constitutes the official Authority to Withdraw for the units listed above.',
      align: 'left',
      fontSize: 9,
      bold: false,
    },
  ],
}

export const DEFAULT_ATW_RELEASE_LAYOUT: CertificateLayoutDefinition = {
  version: 1,
  page: { size: 'A4', marginMm: 20 },
  elements: [
    { type: 'title', text: 'RELEASED AUTHORITY TO WITHDRAW', align: 'center', fontSize: 18, bold: true },
    { type: 'spacer', heightMm: 6 },
    { type: 'field', label: 'ATW No.', binding: 'AtwNumber', fontSize: 11, bold: true },
    { type: 'field', label: 'Reference', binding: 'ReferenceNo', fontSize: 11, bold: false },
    { type: 'field', label: 'Shipping line', binding: 'ShippingLineName', fontSize: 11, bold: false },
    { type: 'field', label: 'Authorized trucker', binding: 'TruckerName', fontSize: 11, bold: false },
    { type: 'field', label: 'CY depot', binding: 'CurrentDepotName', fontSize: 11, bold: false },
    { type: 'field', label: 'Destination', binding: 'Destination', fontSize: 11, bold: false },
    { type: 'field', label: 'Issue date', binding: 'IssueDate', fontSize: 11, bold: false },
    { type: 'field', label: 'Expiration date', binding: 'ExpirationDate', fontSize: 11, bold: false },
    { type: 'field', label: 'Released date', binding: 'ReleasedDate', fontSize: 11, bold: true },
    { type: 'field', label: 'Released at', binding: 'ReleasedAt', fontSize: 11, bold: false },
    { type: 'field', label: 'Released by CY', binding: 'ReleasedByDepotName', fontSize: 11, bold: false },
    { type: 'spacer', heightMm: 4 },
    {
      type: 'text',
      text: 'All container(s) listed below have been released from CY inventory:',
      align: 'left',
      fontSize: 10,
      bold: false,
    },
    { type: 'table', binding: 'ContainerLines', columns: ['ContainerNo', 'Size', 'Type'], fontSize: 10 },
    { type: 'spacer', heightMm: 4 },
    { type: 'field', label: 'Remarks', binding: 'Remarks', fontSize: 11, bold: false },
    { type: 'spacer', heightMm: 8 },
    {
      type: 'text',
      text: 'This document confirms full release of all units under the Authority to Withdraw above. System-generated by ICS.',
      align: 'left',
      fontSize: 9,
      bold: false,
    },
  ],
}

export const DEFAULT_CY_CONTAINER_RELEASE_LAYOUT: CertificateLayoutDefinition = {
  version: 1,
  page: { size: 'A4', marginMm: 20 },
  elements: [
    { type: 'title', text: 'CY CONTAINER RELEASE', align: 'center', fontSize: 18, bold: true },
    { type: 'spacer', heightMm: 6 },
    { type: 'field', label: 'ATW No.', binding: 'AtwNumber', fontSize: 11, bold: true },
    { type: 'field', label: 'Reference', binding: 'ReferenceNo', fontSize: 11, bold: false },
    { type: 'field', label: 'Shipping line', binding: 'ShippingLineName', fontSize: 11, bold: false },
    { type: 'field', label: 'Authorized trucker', binding: 'TruckerName', fontSize: 11, bold: false },
    { type: 'field', label: 'CY depot', binding: 'CurrentDepotName', fontSize: 11, bold: false },
    { type: 'field', label: 'Destination', binding: 'Destination', fontSize: 11, bold: false },
    { type: 'field', label: 'Container no.', binding: 'ContainerNo', fontSize: 11, bold: true },
    { type: 'field', label: 'Size', binding: 'ContainerSize', fontSize: 11, bold: false },
    { type: 'field', label: 'Type', binding: 'ContainerType', fontSize: 11, bold: false },
    { type: 'field', label: 'Released date', binding: 'ReleasedDate', fontSize: 11, bold: true },
    { type: 'field', label: 'Released at', binding: 'ReleasedAt', fontSize: 11, bold: false },
    { type: 'field', label: 'Released by CY', binding: 'ReleasedByDepotName', fontSize: 11, bold: false },
    { type: 'spacer', heightMm: 8 },
    {
      type: 'text',
      text: 'This document confirms release of the container above from CY inventory under the referenced Authority to Withdraw. System-generated by ICS.',
      align: 'left',
      fontSize: 9,
      bold: false,
    },
  ],
}

export function parseLayoutJson(
  layoutJson: string,
  documentType: CertificateDocumentType = 'Atw',
): CertificateLayoutDefinition {
  try {
    const parsed = JSON.parse(layoutJson) as CertificateLayoutDefinition
    if (!parsed.elements) return getDefaultLayout(documentType)
    return parsed
  } catch {
    return getDefaultLayout(documentType)
  }
}

export function serializeLayout(layout: CertificateLayoutDefinition): string {
  return JSON.stringify(layout, null, 2)
}

export function newElement(type: CertificateElementType): CertificateLayoutElement {
  switch (type) {
    case 'title':
      return { type, text: 'Section title', align: 'center', fontSize: 16, bold: true }
    case 'text':
      return { type, text: 'Body text', align: 'left', fontSize: 11, bold: false }
    case 'field':
      return { type, label: 'Label', binding: 'AtwNumber', fontSize: 11, bold: false }
    case 'table':
      return { type, binding: 'ContainerLines', columns: ['ContainerNo', 'Size', 'Type'], fontSize: 10 }
    case 'spacer':
      return { type, heightMm: 4 }
    case 'rule':
      return { type, thicknessPt: 1 }
    case 'image':
      return { type, src: '', align: 'center', widthMm: 40, alt: 'Logo' }
  }
}

export function elementSummary(element: CertificateLayoutElement): string {
  switch (element.type) {
    case 'title':
    case 'text':
      return element.text
    case 'field':
      return `${element.label} → ${element.binding}`
    case 'table':
      return `Table: ${element.columns.join(', ')}`
    case 'spacer':
      return `${element.heightMm}mm spacer`
    case 'rule':
      return 'Horizontal rule'
    case 'image':
      return element.src ? `Image: ${element.src.split('/').pop()}` : 'Image (not uploaded)'
  }
}
