using System.Text.Json;
using ECMS.Domain.Enums;

namespace ECMS.Application.Certificates;

public static class DefaultAtwTemplate
{
    public static CertificateLayoutDefinition Layout => new()
    {
        Version = 1,
        Page = new CertificatePageSettings { Size = "A4", MarginMm = 20 },
        Elements = new List<CertificateLayoutElement>
        {
            new CertificateTitleElement
            {
                Type = "title",
                Text = "AUTHORITY TO WITHDRAW",
                Align = "center",
                FontSize = 18,
                Bold = true,
            },
            new CertificateSpacerElement { Type = "spacer", HeightMm = 6 },
            new CertificateFieldElement { Type = "field", Label = "ATW No.", Binding = "AtwNumber", FontSize = 11, Bold = true },
            new CertificateFieldElement { Type = "field", Label = "Reference", Binding = "ReferenceNo" },
            new CertificateFieldElement { Type = "field", Label = "Shipping line", Binding = "ShippingLineName" },
            new CertificateFieldElement { Type = "field", Label = "Authorized trucker", Binding = "TruckerName" },
            new CertificateFieldElement { Type = "field", Label = "Current CY", Binding = "CurrentDepotName" },
            new CertificateFieldElement { Type = "field", Label = "Destination", Binding = "Destination" },
            new CertificateFieldElement { Type = "field", Label = "Issue date", Binding = "IssueDate" },
            new CertificateFieldElement { Type = "field", Label = "Expiration date", Binding = "ExpirationDate" },
            new CertificateSpacerElement { Type = "spacer", HeightMm = 4 },
            new CertificateTextElement
            {
                Type = "text",
                Text = "The following container(s) are authorized for withdrawal from CY inventory:",
                FontSize = 10,
            },
            new CertificateTableElement
            {
                Type = "table",
                Binding = "ContainerLines",
                Columns = new List<string> { "ContainerNo", "Size", "Type" },
                FontSize = 10,
            },
            new CertificateSpacerElement { Type = "spacer", HeightMm = 4 },
            new CertificateFieldElement { Type = "field", Label = "Remarks", Binding = "Remarks" },
            new CertificateSpacerElement { Type = "spacer", HeightMm = 8 },
            new CertificateTextElement
            {
                Type = "text",
                Text = "This document is system-generated by ICS and constitutes the official Authority to Withdraw for the units listed above.",
                FontSize = 9,
                Align = "left",
            },
        },
    };

    public static string LayoutJson => JsonSerializer.Serialize(Layout, CertificateJson.Options);

    public static AtwCertificateMergeData SampleData => new()
    {
        AtwNumber = "ATW-2026-001",
        ReferenceNo = "WDR-2026-00042",
        ShippingLineName = "Sample Shipping Line",
        TruckerName = "Juan Dela Cruz",
        CurrentDepotName = "Manila CY 1",
        Destination = "Port of Manila",
        IssueDate = "July 6, 2026",
        ExpirationDate = "July 13, 2026",
        Remarks = "Handle with care.",
        ContainerLines = new List<AtwContainerLineMergeData>
        {
            new AtwContainerLineMergeData { ContainerNo = "MSCU1234567", Size = "20", Type = "GP" },
            new AtwContainerLineMergeData { ContainerNo = "TCLU7654321", Size = "40", Type = "HC" },
        },
    };
}

public static class CertificateJson
{
    public static readonly JsonSerializerOptions Options = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        WriteIndented = true,
    };

    public static CertificateLayoutDefinition ParseLayout(string? layoutJson, CertificateDocumentType? documentType = null)
    {
        if (string.IsNullOrWhiteSpace(layoutJson))
            return GetDefaultLayout(documentType ?? CertificateDocumentType.Atw);

        try
        {
            return JsonSerializer.Deserialize<CertificateLayoutDefinition>(layoutJson, Options)
                ?? GetDefaultLayout(documentType ?? CertificateDocumentType.Atw);
        }
        catch
        {
            return GetDefaultLayout(documentType ?? CertificateDocumentType.Atw);
        }
    }

    public static CertificateLayoutDefinition GetDefaultLayout(CertificateDocumentType documentType)
        => documentType switch
        {
            CertificateDocumentType.AtwRelease => DefaultAtwReleaseTemplate.Layout,
            CertificateDocumentType.CyContainerRelease => DefaultCyContainerReleaseTemplate.Layout,
            _ => DefaultAtwTemplate.Layout,
        };

    public static string GetDefaultLayoutJson(CertificateDocumentType documentType)
        => documentType switch
        {
            CertificateDocumentType.AtwRelease => DefaultAtwReleaseTemplate.LayoutJson,
            CertificateDocumentType.CyContainerRelease => DefaultCyContainerReleaseTemplate.LayoutJson,
            _ => DefaultAtwTemplate.LayoutJson,
        };

    public static AtwCertificateMergeData GetSampleData(CertificateDocumentType documentType)
        => documentType switch
        {
            CertificateDocumentType.AtwRelease => DefaultAtwReleaseTemplate.SampleData,
            CertificateDocumentType.CyContainerRelease => DefaultCyContainerReleaseTemplate.SampleData,
            _ => DefaultAtwTemplate.SampleData,
        };

    public static string SerializeLayout(CertificateLayoutDefinition layout)
        => JsonSerializer.Serialize(layout, Options);
}

public static class AtwCertificateFields
{
    public static IReadOnlyList<CertificateMergeFieldDefinition> All { get; } = new List<CertificateMergeFieldDefinition>
    {
        new("AtwNumber", "ATW number", "field"),
        new("ReferenceNo", "ICS reference", "field"),
        new("ShippingLineName", "Shipping line", "field"),
        new("TruckerName", "Authorized trucker", "field"),
        new("CurrentDepotName", "Current CY", "field"),
        new("Destination", "Destination", "field"),
        new("IssueDate", "Issue date", "field"),
        new("ExpirationDate", "Expiration date", "field"),
        new("Remarks", "Remarks", "field"),
        new("ContainerLines", "Container lines table", "table"),
    };
}

public record CertificateMergeFieldDefinition(string Key, string Label, string Kind);
