using System.Text.Json;

namespace ECMS.Application.Certificates;

public static class DefaultAtwReleaseTemplate
{
    public static CertificateLayoutDefinition Layout => new()
    {
        Version = 1,
        Page = new CertificatePageSettings { Size = "A4", MarginMm = 20 },
        Elements = new List<CertificateLayoutElement>
        {
            new CertificateTitleElement
            {
                Type = "title",
                Text = "RELEASED AUTHORITY TO WITHDRAW",
                Align = "center",
                FontSize = 18,
                Bold = true,
            },
            new CertificateSpacerElement { Type = "spacer", HeightMm = 6 },
            new CertificateFieldElement { Type = "field", Label = "ATW No.", Binding = "AtwNumber", FontSize = 11, Bold = true },
            new CertificateFieldElement { Type = "field", Label = "Reference", Binding = "ReferenceNo" },
            new CertificateFieldElement { Type = "field", Label = "Shipping line", Binding = "ShippingLineName" },
            new CertificateFieldElement { Type = "field", Label = "Authorized trucker", Binding = "TruckerName" },
            new CertificateFieldElement { Type = "field", Label = "CY depot", Binding = "CurrentDepotName" },
            new CertificateFieldElement { Type = "field", Label = "Destination", Binding = "Destination" },
            new CertificateFieldElement { Type = "field", Label = "Issue date", Binding = "IssueDate" },
            new CertificateFieldElement { Type = "field", Label = "Expiration date", Binding = "ExpirationDate" },
            new CertificateFieldElement { Type = "field", Label = "Released date", Binding = "ReleasedDate", FontSize = 11, Bold = true },
            new CertificateFieldElement { Type = "field", Label = "Released at", Binding = "ReleasedAt" },
            new CertificateFieldElement { Type = "field", Label = "Released by CY", Binding = "ReleasedByDepotName" },
            new CertificateSpacerElement { Type = "spacer", HeightMm = 4 },
            new CertificateTextElement
            {
                Type = "text",
                Text = "All container(s) listed below have been released from CY inventory:",
                FontSize = 10,
            },
            new CertificateTableElement
            {
                Type = "table",
                Binding = "ContainerLines",
                Columns = new List<string> { "ContainerNo", "Size", "Type" },
                FontSize = 10,
            },
            new CertificateSpacerElement { Type = "spacer", HeightMm = 4 },
            new CertificateFieldElement { Type = "field", Label = "Remarks", Binding = "Remarks" },
            new CertificateSpacerElement { Type = "spacer", HeightMm = 8 },
            new CertificateTextElement
            {
                Type = "text",
                Text = "This document confirms full release of all units under the Authority to Withdraw above. System-generated by ICS.",
                FontSize = 9,
                Align = "left",
            },
        },
    };

    public static string LayoutJson => JsonSerializer.Serialize(Layout, CertificateJson.Options);

    public static AtwCertificateMergeData SampleData => new()
    {
        AtwNumber = "ATW-2026-001",
        ReferenceNo = "WDR-2026-00042",
        ShippingLineName = "Sample Shipping Line",
        TruckerName = "Juan Dela Cruz",
        CurrentDepotName = "Manila CY 1",
        Destination = "Port of Manila",
        IssueDate = "July 6, 2026",
        ExpirationDate = "July 13, 2026",
        ReleasedDate = "July 6, 2026",
        ReleasedAt = "July 6, 2026 2:30 PM",
        ReleasedByDepotName = "Manila CY 1",
        Remarks = "All units released.",
        ContainerLines = new List<AtwContainerLineMergeData>
        {
            new() { ContainerNo = "MSCU1234567", Size = "20", Type = "GP" },
            new() { ContainerNo = "TCLU7654321", Size = "40", Type = "HC" },
        },
    };
}

public static class DefaultCyContainerReleaseTemplate
{
    public static CertificateLayoutDefinition Layout => new()
    {
        Version = 1,
        Page = new CertificatePageSettings { Size = "A4", MarginMm = 20 },
        Elements = new List<CertificateLayoutElement>
        {
            new CertificateTitleElement
            {
                Type = "title",
                Text = "CY CONTAINER RELEASE",
                Align = "center",
                FontSize = 18,
                Bold = true,
            },
            new CertificateSpacerElement { Type = "spacer", HeightMm = 6 },
            new CertificateFieldElement { Type = "field", Label = "ATW No.", Binding = "AtwNumber", FontSize = 11, Bold = true },
            new CertificateFieldElement { Type = "field", Label = "Reference", Binding = "ReferenceNo" },
            new CertificateFieldElement { Type = "field", Label = "Shipping line", Binding = "ShippingLineName" },
            new CertificateFieldElement { Type = "field", Label = "Authorized trucker", Binding = "TruckerName" },
            new CertificateFieldElement { Type = "field", Label = "CY depot", Binding = "CurrentDepotName" },
            new CertificateFieldElement { Type = "field", Label = "Destination", Binding = "Destination" },
            new CertificateFieldElement { Type = "field", Label = "Container no.", Binding = "ContainerNo", FontSize = 11, Bold = true },
            new CertificateFieldElement { Type = "field", Label = "Size", Binding = "ContainerSize" },
            new CertificateFieldElement { Type = "field", Label = "Type", Binding = "ContainerType" },
            new CertificateFieldElement { Type = "field", Label = "Released date", Binding = "ReleasedDate", FontSize = 11, Bold = true },
            new CertificateFieldElement { Type = "field", Label = "Released at", Binding = "ReleasedAt" },
            new CertificateFieldElement { Type = "field", Label = "Released by CY", Binding = "ReleasedByDepotName" },
            new CertificateSpacerElement { Type = "spacer", HeightMm = 8 },
            new CertificateTextElement
            {
                Type = "text",
                Text = "This document confirms release of the container above from CY inventory under the referenced Authority to Withdraw. System-generated by ICS.",
                FontSize = 9,
                Align = "left",
            },
        },
    };

    public static string LayoutJson => JsonSerializer.Serialize(Layout, CertificateJson.Options);

    public static AtwCertificateMergeData SampleData => new()
    {
        AtwNumber = "ATW-2026-001",
        ReferenceNo = "WDR-2026-00042",
        ShippingLineName = "Sample Shipping Line",
        TruckerName = "Juan Dela Cruz",
        CurrentDepotName = "Manila CY 1",
        Destination = "Port of Manila",
        ContainerNo = "MSCU1234567",
        ContainerSize = "20",
        ContainerType = "GP",
        ReleasedDate = "July 6, 2026",
        ReleasedAt = "July 6, 2026 2:30 PM",
        ReleasedByDepotName = "Manila CY 1",
    };
}

public static class ReleaseCertificateFields
{
    private static readonly CertificateMergeFieldDefinition[] ReleaseOnly =
    {
        new("ReleasedDate", "Released date", "field"),
        new("ReleasedAt", "Released at", "field"),
        new("ReleasedByDepotName", "Released by CY", "field"),
    };

    private static readonly CertificateMergeFieldDefinition[] ContainerOnly =
    {
        new("ContainerNo", "Container number", "field"),
        new("ContainerSize", "Container size", "field"),
        new("ContainerType", "Container type", "field"),
    };

    public static IReadOnlyList<CertificateMergeFieldDefinition> AtwRelease { get; } =
        AtwCertificateFields.All.Concat(ReleaseOnly).ToList();

    public static IReadOnlyList<CertificateMergeFieldDefinition> CyContainerRelease { get; } =
        AtwCertificateFields.All
            .Where(f => f.Key is not ("ContainerLines" or "Remarks" or "IssueDate" or "ExpirationDate"))
            .Concat(ContainerOnly)
            .Concat(ReleaseOnly)
            .ToList();
}
